image: python:3.8-buster

before_script:
    - pip install mkdocs markdown-include

pages:
    stage: deploy
    script:
        - mkdocs build --strict --verbose
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_REF_NAME == "main"
