site_name: Hybran
site_url: https://lpcdrp.gitlab.io/hybran
site_description: hybrid prokaryotic genome annotation
repo_url: https://gitlab.com/LPCDRP/hybran
site_dir: public
nav:
    - Getting Started: index.md
    - Commands and Auxiliary Programs: cmds.md
    - Release Notes: release.md
    - Installation: install.md
    - Special Considerations: faq.md
    - Issues and Questions: 'https://gitlab.com/LPCDRP/hybran/issues'
    - Core Components:
        - pseudoscan: pseudoscan.md
markdown_extensions:
    - toc:
        permalink: True
    - markdown_include.include:
        base_path: docs
        inheritHeadingDepth: True
theme: readthedocs
