#!/usr/bin/env python

import os
import sys

from Bio import SeqIO

infile = sys.argv[1]

for record in SeqIO.parse(infile,"genbank"):
    for f in record.features:
        if f.type == 'CDS':
            pseudo = str((('pseudo' in f.qualifiers.keys())
                      or 'pseudogene' in f.qualifiers.keys()))
            inference = ""
            if 'inference' in f.qualifiers.keys():
                if any(['Prodigal' in inf for inf in f.qualifiers['inference']]):
                    inference = "Prokka"
                elif any(['RATT' in inf for inf in f.qualifiers['inference']]):
                    inference = "RATT"
            if 'gene' in f.qualifiers:
                gene = f.qualifiers['gene'][0]
            else:
                gene = ''

            print('\t'.join([
                os.path.basename(os.path.splitext(infile)[0]),
                str(f.location.start+1),
                str(f.location.end),
                str(f.location.strand),
                gene,
                inference,
                pseudo,
            ]))
